# AppVeyor file
# http://www.appveyor.com/docs/appveyor-yml

init:
  - git config --global core.autocrlf true

environment:
  nodejs_version: "4.2"
  GITHUB_TOKEN: "1b17d62d38a4846efa7ea4de4b773b581787b0f1"

build: off

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g gulp
  - npm install
  - npm run vscode:prepublish

test_script:
  - node --version && npm --version
  - gulp